### PR TITLE
Added Dockerfile.prep.v2022.txt For SQL Server 2022 + CU11

### PR DESCRIPTION
**Pull request by IssacKramer**
Hi Tobias.
As I promised, I worked hard to create the SQL Server 2022 version for windows container.
Foo!
Took me almost a week of work.
You can add the new Dockerfile I've created to a new Branch of yours for v2022+CU11
Thank you for all of your work!
Any questions you can ask here or better at my email: tzahik1@gmail.com. 

Best Regards.
Isaac.

### CODE REVIEW

**Comment by tfenster** [comment]
Hi @IssacKramer, thanks for your work! Do I read it correctly that this only works on a machine where the \SQLSetupMedia folder exists?

**Comment by IssacKramer** [comment]
Yes @tfenster , that's right.
No Url's worked for me for this version.
Even the option in SysPrep to get updates from remote:
/UPDATEENABLED=True /UpdateSource='MU' -  didn't worked (even when i put the url).
Logically , it is also safer for the sensitive BUILD stage that real files will be on your desktop after
the hash code is verified to be sure you're putting verified files (and not broken ones because of bad network....)

In fact you need 3 setup folders to be ready for the build as seen in the Dockerfile:
1. The main SQL Server 2022 express setup media extracted that the root SETUP.EXE will be in 'SQLSetupMedia/SQLEXPRADV_x64_ENU/' folder.
2. The CU update (in this case CU11) EXE file (don't need to be extacted) in '\SQLSetupMedia\CU\CU11\SQLServer2022-KB5032679-x64.exe'
3. The Missing Server control files/folders - which is a bunch of folders which include old control dll's under 'Missing' folder.
4 folders needs to be in the folder '\SQLSetupMedia/CU/CU11/Missing/' to fix this strange bug i mentioned there.
you can get them from an old sql server installation from the GAC folder. 
But maybe , for convenience for the public i will upload a zip file with all the folders to just drop it there.
Tedious , i know, but at least it's WORKING! 
SQL Server 2022 express (I believe it work the same for Dev/Ent) on WINDOWS container build **16.0.4105.2** (!)

Cheers.

**Comment by IssacKramer** [comment]
[OldServerControlsFolders.zip](https://github.com/tfenster/mssql-image/files/14184210/OldServerControlsFolders.zip)

**Comment by tfenster** [comment]
I am sorry to say, but I don't like that approach. I want to have something which can run independently on a GitHub runner to create the images and I don't want to fetch dlls "somewhere". But I'll try to reach out to Microsoft to see whether someone can take a look at the bug report that you found. Maybe we'll get a solution there and then it becomes easier.

Again, thanks a lot for your work and of course feel free to maintain a fork of this repo with your approach. I am pretty sure a lot of people will welcome that, it's just not an approach that I would like to promote

**Comment by IssacKramer** [comment]
No Problem.
Feel free to change it whatever you like.
I just wanted a windows version for sql server 2022 fast and working.
Sure it's not ideal. But for me it's fine, I don't need to automate this.
If you have the time you are welcome to dig in and find a better solution.
Bye the way, do you have connection to Microsoft? Do you know if they will
return to support windows containers again?
Many thanks.

**Comment by tfenster** [comment]
From brief discussions I had with them when they announced to drop Windows support, I don't think so

**Pull request closed without merging**
